### ISSUE TITLE
License of this work?

### ISSUE THREAD

**Issue by ahonena** [GPT-Laboratory/RAG-LLM-Development-Guidebook-from-PDFs#1]
Hello, I am working on similar topic, and I would like to utilize the knowledge provided in this project and perhaps also to contribute to it later, but you have not defined its license. Do you plan to license this project under any [open source software license](https://opensource.org/licenses)?

**Comment by toufique69** [comment]
Thank you for your message and for your interest in the project. I have now added a LICENSE file, and the project is available under MIT License.
